Repository dyno-nuggets/refonte-implicaction, pull requests merged in 2021-10, with the labels that each got.

#108 RI-62: ajoute/modifie/supprime une formation depuis la page de profil
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/ExperienceController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/TrainingController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/TrainingService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/WorkExperienceService.java
  frontend-implicaction/src/app/app.component.scss
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/shared/models/uris.ts
  frontend-implicaction/src/app/shared/services/user-contexte.service.ts
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.html
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.ts
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
  frontend-implicaction/src/app/user/components/training-detail/training-detail.component.html
  frontend-implicaction/src/app/user/components/training-detail/training-detail.component.scss
  frontend-implicaction/src/app/user/components/training-detail/training-detail.component.ts
  frontend-implicaction/src/app/user/components/training-form/training-form.component.html
  frontend-implicaction/src/app/user/components/training-form/training-form.component.scss
  frontend-implicaction/src/app/user/components/training-form/training-form.component.spec.ts
  frontend-implicaction/src/app/user/components/training-form/training-form.component.ts
  frontend-implicaction/src/app/user/components/training-list/training-list.component.html
  frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
  frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
  frontend-implicaction/src/app/user/components/user-profile/user-profile.component.ts
  frontend-implicaction/src/app/user/services/experience.service.spec.ts
  frontend-implicaction/src/app/user/services/experience.service.ts
  frontend-implicaction/src/app/user/services/training.service.spec.ts
  frontend-implicaction/src/app/user/services/training.service.ts
  frontend-implicaction/src/app/user/services/user.service.ts
  frontend-implicaction/src/app/user/user.module.ts
  frontend-implicaction/src/assets/variables.scss
  frontend-implicaction/src/styles.scss
Labels: profil

#109 RI-100: ajoute le profil local à spring-boot
  backend-implicaction/src/main/resources/application-local.properties
  backend-implicaction/src/main/resources/application-local.yml
  backend-implicaction/src/main/resources/application.properties
  backend-implicaction/src/main/resources/application.yml
Labels: technical

#110 build: configure le déploiement sur heroku
  Procfile
  backend-implicaction/src/main/resources/application.yml
  system.properties
Labels: technical

#111 RI 20: Editer les infos personnelles
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
  frontend-implicaction/package-lock.json
  frontend-implicaction/src/app/admin/admin.component.spec.ts
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.html
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.scss
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.ts
  frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
  frontend-implicaction/src/app/user/services/user.service.ts
  frontend-implicaction/src/styles.scss
Labels: enhancement, users

#112 RI-91: Ajoute un @username dans le menu déroulant du header.
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/components/header/header.component.scss
Labels: enhancement, users

#113 RI-101: Il est possible de modifier le profil d'un autre utilisateur
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.html
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.ts
  frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
Labels: bug, users

#114 RI-102: corrige le problème du username dans le menu de la barre de navigation qui ressemble à un lien alors qu'il ne s'agit que de texte
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/components/header/header.component.scss
  frontend-implicaction/src/styles.scss
Labels: bug
