Repository dyno-nuggets/refonte-implicaction, pull requests merged in 2021-09, with the labels that each got.

#57 feat: ajoute la gestion des exceptions de l'api
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SwaggerConfiguration.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ExceptionResponse.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/ImplicactionException.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/UnauthorizedException.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/handler/GlobalExceptionHandler.java
  frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
Labels: technical

#59 feat: ajoute le traitement des exceptions du filter
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ExceptionResponse.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/security/JwtAuthenticationFilter.java
Labels: technical

#61 feat: ajoute la page communauté
  frontend-implicaction/package-lock.json
  frontend-implicaction/package.json
  frontend-implicaction/src/app/admin/guards/Logged-in.guard.spec.ts
  frontend-implicaction/src/app/admin/guards/logged-in.guard.ts
  frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.html
  frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.scss
  frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
  frontend-implicaction/src/app/app-routing.module.ts
  frontend-implicaction/src/app/app.component.html
  frontend-implicaction/src/app/app.component.scss
  frontend-implicaction/src/app/community/community-routing.module.ts
  frontend-implicaction/src/app/community/community.component.html
  frontend-implicaction/src/app/community/community.component.scss
  frontend-implicaction/src/app/community/community.component.spec.ts
  frontend-implicaction/src/app/community/community.component.ts
  frontend-implicaction/src/app/community/community.module.ts
  frontend-implicaction/src/app/config/constants.ts
  frontend-implicaction/src/app/icons/icons.module.ts
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/components/header/header.component.scss
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.html
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.scss
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.spec.ts
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.ts
  frontend-implicaction/src/app/shared/models/pageable.ts
  frontend-implicaction/src/app/shared/models/user.ts
  frontend-implicaction/src/app/shared/shared.module.ts
  frontend-implicaction/src/assets/variables.scss
  frontend-implicaction/src/styles.scss
Labels: enhancement, community

#62 feat(user/profile): affiche le composant des infos personnelles
  frontend-implicaction/package-lock.json
  frontend-implicaction/src/app/app-routing.module.ts
  frontend-implicaction/src/app/app.component.html
  frontend-implicaction/src/app/app.component.scss
  frontend-implicaction/src/app/icons/icons.module.ts
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.html
  frontend-implicaction/src/app/shared/components/user-card/user-card.component.scss
  frontend-implicaction/src/app/shared/models/user.ts
  frontend-implicaction/src/app/shared/services/user.service.ts
  frontend-implicaction/src/app/user/profile/components/personal-card/personal-card.component.html
  frontend-implicaction/src/app/user/profile/components/personal-card/personal-card.component.scss
  frontend-implicaction/src/app/user/profile/components/personal-card/personal-card.component.spec.ts
  frontend-implicaction/src/app/user/profile/components/personal-card/personal-card.component.ts
  frontend-implicaction/src/app/user/profile/profile-routing.module.ts
  frontend-implicaction/src/app/user/profile/profile.component.html
  frontend-implicaction/src/app/user/profile/profile.component.scss
  frontend-implicaction/src/app/user/profile/profile.component.spec.ts
  frontend-implicaction/src/app/user/profile/profile.component.ts
  frontend-implicaction/src/app/user/profile/profile.module.ts
  frontend-implicaction/src/app/user/user-routing.module.ts
  frontend-implicaction/src/app/user/user.module.ts
  frontend-implicaction/src/assets/variables.scss
  frontend-implicaction/src/styles.scss
Labels: enhancement, users

#60 feat: permet la récupération des données d'un utilisateur
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/TrainingDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/WorkExperienceDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/UserNotFoundException.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/handler/GlobalExceptionHandler.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/UserRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapterTest.java
Labels: users

#63 feat(auth): ajoute le userId de l'utilisateur connecté dans le payload de login et le rend accessible dans le AuthService
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/AuthenticationResponseDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/components/header/header.component.ts
  frontend-implicaction/src/app/shared/models/login-response.ts
  frontend-implicaction/src/app/shared/services/auth.service.ts
  frontend-implicaction/src/app/user/user-routing.module.ts
  frontend-implicaction/src/app/user/user.module.ts
Labels: auth

#65 fix(auth/refresh_token): joint le userId au payload de la réponse d'une requête de refresh token
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/FakeController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/FakeService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
Labels: auth

#71 feat(user/relation): permet d'effectuer une demande d'ami en cliquant sur "ajouter" depuis la liste des membres
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/icons/icons.module.ts
  frontend-implicaction/src/app/shared/models/uris.ts
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.scss
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/models/relation.ts
  frontend-implicaction/src/app/user/services/relation.service.spec.ts
  frontend-implicaction/src/app/user/services/relation.service.ts
  frontend-implicaction/src/assets/variables.scss
  frontend-implicaction/src/styles.scss
Labels: users, community

#66 refact: complète le modèle user
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
Labels: users

#75 feat(user/relation): permet de récupérer la list d'amis d'un utilisateur
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
Labels: users, community

#77 feat: récupère la liste des demandes d'amis non acceptées et envoyée par l'utilisateur connecté
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/TrainingDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
Labels: users

#78 refact(user/list): ajoute l'affichage des amis et demandes
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/shared/components/header/header.component.html
  frontend-implicaction/src/app/shared/models/uris.ts
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/services/user.service.ts
  frontend-implicaction/src/app/user/user-routing.module.ts
  frontend-implicaction/src/app/user/user.module.ts
Labels: users, community

#79 feat(users/community): ajoute la confirmation d'une invitation d'ami envoyée à l'utilisateur
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/shared/models/uris.ts
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/services/user.service.ts
Labels: users, community

#80 feat(users/community): permet la suppression d'un ami
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/shared/models/uris.ts
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/services/user.service.ts
Labels: users, community

#81 feat(users/community): permet la suppression d'un ami, de refuser une invitation ou d'en annuler une pas encore confirmée
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
Labels: users, community

#82 [RI-23]: modifie la recherche de tous les utilisateurs pour ne plus avoir à récupérer la liste de toutes les relations
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/RelationTypeEnum.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
  frontend-implicaction/src/app/shared/models/user.ts
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/models/relation-type.enum.ts
Labels: users, community

#85 Ri-54: introduit la notion de rôles dans l'application
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/AuthenticationResponseDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ReqisterRequestDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Group.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/RefreshToken.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Relation.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Role.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Signup.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Training.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/WorkExperience.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RoleRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/security/JwtProvider.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserDetailsServiceImpl.java
  backend-implicaction/src/main/resources/application.properties
  frontend-implicaction/src/app/app-routing.module.ts
  frontend-implicaction/src/app/auth/auth.module.ts
  frontend-implicaction/src/app/auth/components/signup/signup.component.ts
  frontend-implicaction/src/app/core/guards/auth.guard.service.ts
  frontend-implicaction/src/app/core/guards/auth.guard.spec.ts
  frontend-implicaction/src/app/core/guards/logged-in.guard.ts
  frontend-implicaction/src/app/shared/enums/role-enum.enum.ts
  frontend-implicaction/src/app/shared/models/login-response.ts
  frontend-implicaction/src/app/shared/models/signup-request-payload.ts
  frontend-implicaction/src/app/shared/models/user.ts
  frontend-implicaction/src/app/shared/services/auth.service.ts
Labels: auth

#84 RI-30: sauvergarde les modifications apportées aux formations
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/TrainingController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/TrainingDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Training.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/TrainingRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/TrainingService.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapterTest.java
Labels: users

#83 refact(user/list): corrige le responsive de la page
  frontend-implicaction/src/app/shared/components/loading/loading.component.html
  frontend-implicaction/src/app/shared/components/loading/loading.component.scss
  frontend-implicaction/src/app/shared/components/loading/loading.component.spec.ts
  frontend-implicaction/src/app/shared/components/loading/loading.component.ts
  frontend-implicaction/src/app/shared/shared.module.ts
  frontend-implicaction/src/app/user/components/user-list/user-list.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.scss
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
  frontend-implicaction/src/app/user/user.module.ts
Labels: users, community

#87 RI-31: sauvergarde les modifications apportées aux expériences professionelles
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/TrainingController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/WorkExperienceRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/WorkExperienceService.java
Labels: users

#97 RI-69: Ajouter des expériences dans le mode édition
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.scss
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
Labels: users

#100 RI-72: modifie le design du toaster ainsi que ses transitions.
  frontend-implicaction/src/app/app.component.html
  frontend-implicaction/src/app/app.component.scss
  frontend-implicaction/src/assets/toaster.scss
  frontend-implicaction/src/index.html
Labels: enhancement

#101 feat: RI-73: Récupérer tous les jobs depuis la base
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/JobPostingController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
Labels: Job-Board

#99 fix: corrige le problème d'ajout d'un nouvel element en le bloquant à un element vide maximum
  frontend-implicaction/src/app/shared/classes/utils.spec.ts
  frontend-implicaction/src/app/shared/classes/utils.ts
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
  frontend-implicaction/src/app/user/components/training-list/training-list.component.html
  frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
Labels: users

#102 RI-22: redéfinis le modèle user -> job_seeker -> recruiter
  backend-implicaction/pom.xml
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/RelationAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/AuthController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/JobSeekerDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ReqisterRequestDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Company.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/JobSeeker.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Recruiter.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/RoleEnum.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Signup.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/JobSeekerRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RecruiterRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/SignUpRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/UserRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserDetailsServiceImpl.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/RelationAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapterTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/RelationRepositoryTest.java
  backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/UserRepositoryTest.java
  data.sql
  frontend-implicaction/src/app/auth/components/login/login.component.html
  frontend-implicaction/src/app/auth/components/login/login.component.ts
  frontend-implicaction/src/app/auth/components/signup/signup.component.html
  frontend-implicaction/src/app/auth/components/signup/signup.component.ts
  frontend-implicaction/src/app/shared/enums/role-enum.enum.ts
  frontend-implicaction/src/app/shared/models/signup-request-payload.ts
  frontend-implicaction/src/app/shared/models/user.ts
  frontend-implicaction/src/app/user/components/personal-card/personal-card.component.html
  frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
  frontend-implicaction/src/app/user/components/user-card/user-card.component.html
  frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
Labels: users

#104 fix: dump de la BD
  data.sql
Labels: bug

#103 Ri 74: met en place la capture des erreurs http au niveau du front
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/handler/GlobalExceptionHandler.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/UserRepository.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
  frontend-implicaction/src/app/auth/auth.module.ts
  frontend-implicaction/src/app/auth/components/login/login.component.html
  frontend-implicaction/src/app/auth/components/login/login.component.ts
  frontend-implicaction/src/app/auth/components/signup/signup.component.html
  frontend-implicaction/src/app/auth/components/signup/signup.component.ts
  frontend-implicaction/src/app/core/core.module.ts
  frontend-implicaction/src/app/core/interceptors/http-error.interceptor.spec.ts
  frontend-implicaction/src/app/core/interceptors/http-error.interceptor.ts
  frontend-implicaction/src/app/shared/components/alert/alert.component.html
  frontend-implicaction/src/app/shared/components/alert/alert.component.scss
  frontend-implicaction/src/app/shared/components/alert/alert.component.spec.ts
  frontend-implicaction/src/app/shared/components/alert/alert.component.ts
  frontend-implicaction/src/app/shared/models/alert.ts
  frontend-implicaction/src/app/shared/services/alert.service.spec.ts
  frontend-implicaction/src/app/shared/services/alert.service.ts
  frontend-implicaction/src/app/shared/shared.module.ts
Labels: technical

#105 RI-29: sauvegarde les informations personnelles dans la BD
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
Labels: enhancement, users

#106 RI-76: ajoute/modifie une expérience à l'aide de la sidebar
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/security/JwtProvider.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/WorkExperienceService.java
  backend-implicaction/src/main/resources/application-local.properties
  frontend-implicaction/package-lock.json
  frontend-implicaction/package.json
  frontend-implicaction/src/app/app.component.html
  frontend-implicaction/src/app/app.component.scss
  frontend-implicaction/src/app/app.component.ts
  frontend-implicaction/src/app/app.module.ts
  frontend-implicaction/src/app/auth/components/login/login.component.ts
  frontend-implicaction/src/app/config/constants.ts
  frontend-implicaction/src/app/core/interceptors/http-error.interceptor.ts
  frontend-implicaction/src/app/core/services/api-endpoints.service.ts
  frontend-implicaction/src/app/icons/icons.module.ts
  frontend-implicaction/src/app/shared/classes/utils.ts
  frontend-implicaction/src/app/shared/directives/sidebar-content.directive.spec.ts
  frontend-implicaction/src/app/shared/directives/sidebar-content.directive.ts
  frontend-implicaction/src/app/shared/models/sidebar-props.ts
  frontend-implicaction/src/app/shared/pipes/br.pipe.spec.ts
  frontend-implicaction/src/app/shared/pipes/br.pipe.ts
  frontend-implicaction/src/app/shared/services/auth.service.ts
  frontend-implicaction/src/app/shared/services/sidebar.service.spec.ts
  frontend-implicaction/src/app/shared/services/sidebar.service.ts
  frontend-implicaction/src/app/shared/services/user-contexte.service.spec.ts
  frontend-implicaction/src/app/shared/services/user-contexte.service.ts
  frontend-implicaction/src/app/shared/shared.module.ts
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.scss
  frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.html
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.scss
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.spec.ts
  frontend-implicaction/src/app/user/components/experience-form/experience-form.component.ts
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.scss
  frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
  frontend-implicaction/src/app/user/components/user-profile/user-profile.component.ts
  frontend-implicaction/src/app/user/services/user.service.ts
  frontend-implicaction/src/app/user/user.module.ts
  frontend-implicaction/src/assets/variables.scss
  frontend-implicaction/src/styles.scss
Labels: enhancement, technical, users

#107 RI-77: Supprimer une expérience en base
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/ExperienceController.java
  backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/WorkExperienceService.java
  docker-compose.yml
  frontend-implicaction/package.json
Labels: users
